### ISSUE TITLE
SSL problem when issuing 'sly install'

### ISSUE THREAD

**Issue by catskul** [Haar/Sprintly-Terminal#11]
After entering email address and API key

```
sly install
```

Dies with

```
error: Problem with the SSL CA cert (path? access rights?)
```

from command line

```
curl https://sprint.ly
```

works just fine, but from ruby 

```
request = Curl::easy::new('https://sprint.ly')
request.perform
```

dies with the same SSL CA cert error unless we set verify_peer to false:

```
request.ssl_verify_peer = false
```

**Comment by Haar** [comment]
What system are you experiencing the problem on? Looking around that error mainly seems related to an outdated CA cert on the machine in question.

If you post your system details I'll keep looking :).

**Comment by catskul** [comment]
Ubuntu 13.10

ca-certificates is up-to-date (20130906ubuntu0.1)

I think it might be related to the curl ruby package referencing a library
that doesn't exist
